version: "3.8"

services:
  moviepilot:
    image: ${DOCKER_IMAGE:-txyelva/movpilottt:latest}
    container_name: moviepilot-mod
    hostname: moviepilot
    restart: unless-stopped
    network_mode: bridge
    ports:
      - "${NGINX_PORT:-3000}:3000"
    volumes:
      - "${CONFIG_DIR:-/volume1/docker/moviepilot/config}:/config"
      - "/volume1:/volume1"
    environment:
      - MOVIEPILOT_AUTO_UPDATE=false
      - NGINX_PORT=3000
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - UMASK=${UMASK:-000}
      - TZ=${TZ:-Asia/Shanghai}
